name: Rsync
inputs:
  user:
    required: true
  host:
    required: true
  key:
    required: true
  port:
    default: 22
  local_dir:
    default: './'
  remote_dir:
    required: true
  args:
    default: '-r'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}