name: SSH
inputs:
  user:
    required: true
  host:
    required: true
  key:
    required: true
  port:
    default: 22
  command:
    default: 'whoami'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}